# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43432bf64860da38f331f482269ee7fafd94d016b9de4b1011286127500055ba0ac10c03447933be2e7dbcc589a2650de0d5b9b3ff9b9b9ce6d56201406e8109

test:
  secret_key_base: 74ac34a23a8a8202123fc72609ae05e17fc82390952e0f8a73851cd3db43cb89b5322632874c2a1b83c38dac2989d9cb9ea259136821bef979dd46ef6ccafe6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
